### ISSUE TITLE
Weapons don't attach to body when logging in

### ISSUE THREAD

**Issue by alberttheprince** [Testaross/obackweapon#11]
Weapons will appear to "float" in the air when logging in for the first time, even if weapons are in your inventory and require you to pull the weapon out and but it back into your inventory to make them go on your back.

**Comment by minipunch** [comment]
For QB I noticed the weapons don't appear at all (or maybe they do float but I missed that aspect)

This bit of code fixes it though for anyone wondering:

```RegisterNetEvent('QBCore:Client:OnPlayerLoaded')
AddEventHandler('QBCore:Client:OnPlayerLoaded', function()
    local startTime = GetGameTimer()
    while GetGameTimer() - startTime < 10000 do
        Wait(1)
    end
    respawningCheckWeapon()
end)
```
